// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwv8B7O22HY6ViyOM7qUwM2hQg2CueBRY',
    appId: '1:658592590051:web:978c37ffde9d502e6d7dd6',
    messagingSenderId: '658592590051',
    projectId: 'chatappbtl-e2c94',
    authDomain: 'chatappbtl-e2c94.firebaseapp.com',
    storageBucket: 'chatappbtl-e2c94.appspot.com',
    measurementId: 'G-GKX3P0DJXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHQNtDlRnICYRJ3XACpXc-DCgMf6SEuFQ',
    appId: '1:658592590051:android:533129499a7e9b0f6d7dd6',
    messagingSenderId: '658592590051',
    projectId: 'chatappbtl-e2c94',
    storageBucket: 'chatappbtl-e2c94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIR7grBhWlS3h5nxib4v_RGKo6EO_8VXg',
    appId: '1:658592590051:ios:7893695fb051a56e6d7dd6',
    messagingSenderId: '658592590051',
    projectId: 'chatappbtl-e2c94',
    storageBucket: 'chatappbtl-e2c94.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIR7grBhWlS3h5nxib4v_RGKo6EO_8VXg',
    appId: '1:658592590051:ios:7893695fb051a56e6d7dd6',
    messagingSenderId: '658592590051',
    projectId: 'chatappbtl-e2c94',
    storageBucket: 'chatappbtl-e2c94.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwv8B7O22HY6ViyOM7qUwM2hQg2CueBRY',
    appId: '1:658592590051:web:33db740edf760cde6d7dd6',
    messagingSenderId: '658592590051',
    projectId: 'chatappbtl-e2c94',
    authDomain: 'chatappbtl-e2c94.firebaseapp.com',
    storageBucket: 'chatappbtl-e2c94.appspot.com',
    measurementId: 'G-DL38ZD92FM',
  );
}
